In [1]:
import pandas as pd

import warnings
warnings.filterwarnings('ignore')

In [4]:
# Importing the metadata that does not have continents and subregions only countries
metadata_country =pd.read_csv(r"C:\Users\chine\Downloads\Catboost Project\Cleaned Data\Cleaned Data\MetaData.csv" ,encoding ="latin-1")
metadata_country

,country_name,Country Code,Region,IncomeGroup,SpecialNotes
0,Aruba,ABW,Latin America & Caribbean,High income,NaN
1,Afghanistan,AFG,South Asia,Low income,The reporting period for national accounts dat...
2,Angola,AGO,Sub-Saharan Africa,Lower middle income,The World Bank systematically assesses the app...
3,Albania,ALB,Europe & Central Asia,Upper middle income,NaN
4,Andorra,AND,Europe & Central Asia,High income,NaN
...,...,...,...,...,...
212,Kosovo,XKX,Europe & Central Asia,Upper middle income,NaN
213,"Yemen, Rep.",YEM,Middle East & North Africa,Low income,The World Bank systematically assesses the app...
214,South Africa,ZAF,Sub-Saharan Africa,Upper middle income,Fiscal year end: March 31; reporting period fo...
215,Zambia,ZMB,Sub-Saharan Africa,Lower middle income,National accounts data were rebased to reflect...
216,Zimbabwe,ZWE,Sub-Saharan Africa,Lower middle income,National Accounts data are reported in Zimbabw...

In [5]:
# checking the total number of the countries in metadata
metadata_country['country_name'].nunique()

217

In [3]:
remittance= pd.read_csv(r"C:\Users\chine\Downloads\Catboost Project\Cleaned Data\Cleaned Data\merged_with_data.csv")
remittance

,Year,country_code,country_name,gdp,new_income_group,new_region,population,remittance_growth_rate,remittance_paid,remittance_per_capita,remittance_received,remittance_to_gdp_ratio,remittance_volatility,unemployment_rate,unemployment_rate_change
0,1970,AFG,Afghanistan,0.000000,Low income,South Asia,10752971.0,0.000000,0.00,0.000000,0.000000e+00,0.000000e+00,2.934855e+08,0.000,0.000
1,1971,AFG,Afghanistan,0.000000,Low income,South Asia,11015857.0,0.000000,0.00,0.000000,0.000000e+00,0.000000e+00,2.934855e+08,0.000,0.000
2,1972,AFG,Afghanistan,0.000000,Low income,South Asia,11286753.0,0.000000,0.00,0.000000,0.000000e+00,0.000000e+00,2.934855e+08,0.000,0.000
3,1973,AFG,Afghanistan,0.000000,Low income,South Asia,11575305.0,0.000000,0.00,0.000000,0.000000e+00,0.000000e+00,2.934855e+08,0.000,0.000
4,1974,AFG,Afghanistan,0.000000,Low income,South Asia,11869879.0,0.000000,0.00,0.000000,0.000000e+00,0.000000e+00,2.934855e+08,0.000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14093,2018,ZWE,Zimbabwe,4.179939,Lower middle income,Sub-Saharan Africa,15052184.0,-17.468271,29278892.45,94.850224,1.427703e+09,3.415607e+08,8.881924e+08,6.784,0.505
14094,2019,ZWE,Zimbabwe,6.490458,Lower middle income,Sub-Saharan Africa,15354608.0,-0.748830,13480565.66,92.285779,1.417012e+09,2.183223e+08,8.881924e+08,7.370,0.586
14095,2020,ZWE,Zimbabwe,8.517271,Lower middle income,Sub-Saharan Africa,15669666.0,29.288915,21707094.03,116.916301,1.832039e+09,2.150970e+08,8.881924e+08,7.898,0.528
14096,2021,ZWE,Zimbabwe,6.985948,Lower middle income,Sub-Saharan Africa,15993524.0,8.185447,0.00,123.925159,1.982000e+09,2.837124e+08,8.881924e+08,8.067,0.169
14097,2022,ZWE,Zimbabwe,9.901347,Lower middle income,Sub-Saharan Africa,16320537.0,3.300000,0.00,125.449671,2.047406e+09,2.067806e+08,8.881924e+08,7.945,-0.122

In [6]:
# checking the total number of the remittance data
remittance['country_name'].nunique()

266

There are 217 countries in the metadata  But we have 266  in the remittance data set
We need to find the countries that are not supposed to be in the remittance data

In [7]:
# Getting the names of the countries in the remittance datafarme and storing them in a list
remittance_country_list = remittance['country_name'].unique()
remittance_country_list

array(['Afghanistan', 'Africa Eastern and Southern',
       'Africa Western and Central', 'Albania', 'Algeria',
       'American Samoa', 'Andorra', 'Angola', 'Antigua and Barbuda',
       'Arab World', 'Argentina', 'Armenia', 'Aruba', 'Australia',
       'Austria', 'Azerbaijan', 'Bahamas, The', 'Bahrain', 'Bangladesh',
       'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bermuda',
       'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana',
       'Brazil', 'British Virgin Islands', 'Brunei Darussalam',
       'Bulgaria', 'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia',
       'Cameroon', 'Canada', 'Caribbean small states', 'Cayman Islands',
       'Central African Republic', 'Central Europe and the Baltics',
       'Chad', 'Channel Islands', 'Chile', 'China', 'Colombia', 'Comoros',
       'Congo, Dem. Rep.', 'Congo, Rep.', 'Costa Rica', "Cote d'Ivoire",
       'Croatia', 'Cuba', 'Curacao', 'Cyprus', 'Czechia', 'Denmark',
       'Djibouti', 'Dominica', 'Dominican Republic',
       'Early-demographic dividend', 'East Asia & Pacific',
       'East Asia & Pacific (IDA & IBRD countries)',
       'East Asia & Pacific (excluding high income)', 'Ecuador',
       'Egypt, Arab Rep.', 'El Salvador', 'Equatorial Guinea', 'Eritrea',
       'Estonia', 'Eswatini', 'Ethiopia', 'Euro area',
       'Europe & Central Asia',
       'Europe & Central Asia (IDA & IBRD countries)',
       'Europe & Central Asia (excluding high income)', 'European Union',
       'Faroe Islands', 'Fiji', 'Finland',
       'Fragile and conflict affected situations', 'France',
       'French Polynesia', 'Gabon', 'Gambia, The', 'Georgia', 'Germany',
       'Ghana', 'Gibraltar', 'Greece', 'Greenland', 'Grenada', 'Guam',
       'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti',
       'Heavily indebted poor countries (HIPC)', 'High income',
       'Honduras', 'Hong Kong SAR, China', 'Hungary', 'IBRD only',
       'IDA & IBRD total', 'IDA blend', 'IDA only', 'IDA total',
       'Iceland', 'India', 'Indonesia', 'Iran, Islamic Rep.', 'Iraq',
       'Ireland', 'Isle of Man', 'Israel', 'Italy', 'Jamaica', 'Japan',
       'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati',
       "Korea, Dem. People's Rep.", 'Korea, Rep.', 'Kosovo', 'Kuwait',
       'Kyrgyz Republic', 'Lao PDR', 'Late-demographic dividend',
       'Latin America & Caribbean',
       'Latin America & Caribbean (excluding high income)',
       'Latin America & the Caribbean (IDA & IBRD countries)', 'Latvia',
       'Least developed countries: UN classification', 'Lebanon',
       'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania',
       'Low & middle income', 'Low income', 'Lower middle income',
       'Luxembourg', 'Macao SAR, China', 'Madagascar', 'Malawi',
       'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands',
       'Mauritania', 'Mauritius', 'Mexico', 'Micronesia, Fed. Sts.',
       'Middle East & North Africa',
       'Middle East & North Africa (IDA & IBRD countries)',
       'Middle East & North Africa (excluding high income)',
       'Middle income', 'Moldova', 'Monaco', 'Mongolia', 'Montenegro',
       'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal',
       'Netherlands', 'New Caledonia', 'New Zealand', 'Nicaragua',
       'Niger', 'Nigeria', 'North America', 'North Macedonia',
       'Northern Mariana Islands', 'Norway', 'Not classified',
       'OECD members', 'Oman', 'Other small states',
       'Pacific island small states', 'Pakistan', 'Palau', 'Panama',
       'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland',
       'Portugal', 'Post-demographic dividend',
       'Pre-demographic dividend', 'Puerto Rico', 'Qatar', 'Romania',
       'Russian Federation', 'Rwanda', 'Samoa', 'San Marino',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore',
       'Sint Maarten (Dutch part)', 'Slovak Republic', 'Slovenia',
       'Small states', 'Solomon Islands', 'Somalia', 'South Africa',
       'South Asia', 'South Asia (IDA & IBRD)', 'South Sudan', 'Spain',
       'Sri Lanka', 'St. Kitts and Nevis', 'St. Lucia',
       'St. Martin (French part)', 'St. Vincent and the Grenadines',
       'Sub-Saharan Africa', 'Sub-Saharan Africa (IDA & IBRD countries)',
       'Sub-Saharan Africa (excluding high income)', 'Sudan', 'Suriname',
       'Sweden', 'Switzerland', 'Syrian Arab Republic', 'Tajikistan',
       'Tanzania', 'Thailand', 'Timor-Leste', 'Togo', 'Tonga',
       'Trinidad and Tobago', 'Tunisia', 'Turkiye', 'Turkmenistan',
       'Turks and Caicos Islands', 'Tuvalu', 'Uganda', 'Ukraine',
       'United Arab Emirates', 'United Kingdom', 'United States',
       'Upper middle income', 'Uruguay', 'Uzbekistan', 'Vanuatu',
       'Venezuela, RB', 'Vietnam', 'Virgin Islands (U.S.)',
       'West Bank and Gaza', 'World', 'Yemen, Rep.', 'Zambia', 'Zimbabwe'],
      dtype=object)

In [10]:
len(remittance_country_list)

266

In [8]:
# Lets get the unique names of countries in metadata  and Create a list to store the  countries 
metadata_country_list = metadata_country['country_name'].unique() 
metadata_country_list

array(['Aruba', 'Afghanistan', 'Angola', 'Albania', 'Andorra',
       'United Arab Emirates', 'Argentina', 'Armenia', 'American Samoa',
       'Antigua and Barbuda', 'Australia', 'Austria', 'Azerbaijan',
       'Burundi', 'Belgium', 'Benin', 'Burkina Faso', 'Bangladesh',
       'Bulgaria', 'Bahrain', 'Bahamas, The', 'Bosnia and Herzegovina',
       'Belarus', 'Belize', 'Bermuda', 'Bolivia', 'Brazil', 'Barbados',
       'Brunei Darussalam', 'Bhutan', 'Botswana',
       'Central African Republic', 'Canada', 'Switzerland',
       'Channel Islands', 'Chile', 'China', "Cote d'Ivoire", 'Cameroon',
       'Congo, Dem. Rep.', 'Congo, Rep.', 'Colombia', 'Comoros',
       'Cabo Verde', 'Costa Rica', 'Cuba', 'Curacao', 'Cayman Islands',
       'Cyprus', 'Czechia', 'Germany', 'Djibouti', 'Dominica', 'Denmark',
       'Dominican Republic', 'Algeria', 'Ecuador', 'Egypt, Arab Rep.',
       'Eritrea', 'Spain', 'Estonia', 'Ethiopia', 'Finland', 'Fiji',
       'France', 'Faroe Islands', 'Micronesia, Fed. Sts.', 'Gabon',
       'United Kingdom', 'Georgia', 'Ghana', 'Gibraltar', 'Guinea',
       'Gambia, The', 'Guinea-Bissau', 'Equatorial Guinea', 'Greece',
       'Grenada', 'Greenland', 'Guatemala', 'Guam', 'Guyana',
       'Hong Kong SAR, China', 'Honduras', 'Croatia', 'Haiti', 'Hungary',
       'Indonesia', 'Isle of Man', 'India', 'Ireland',
       'Iran, Islamic Rep.', 'Iraq', 'Iceland', 'Israel', 'Italy',
       'Jamaica', 'Jordan', 'Japan', 'Kazakhstan', 'Kenya',
       'Kyrgyz Republic', 'Cambodia', 'Kiribati', 'St. Kitts and Nevis',
       'Korea, Rep.', 'Kuwait', 'Lao PDR', 'Lebanon', 'Liberia', 'Libya',
       'St. Lucia', 'Liechtenstein', 'Sri Lanka', 'Lesotho', 'Lithuania',
       'Luxembourg', 'Latvia', 'Macao SAR, China',
       'St. Martin (French part)', 'Morocco', 'Monaco', 'Moldova',
       'Madagascar', 'Maldives', 'Mexico', 'Marshall Islands',
       'North Macedonia', 'Mali', 'Malta', 'Myanmar', 'Montenegro',
       'Mongolia', 'Northern Mariana Islands', 'Mozambique', 'Mauritania',
       'Mauritius', 'Malawi', 'Malaysia', 'Namibia', 'New Caledonia',
       'Niger', 'Nigeria', 'Nicaragua', 'Netherlands', 'Norway', 'Nepal',
       'Nauru', 'New Zealand', 'Oman', 'Pakistan', 'Panama', 'Peru',
       'Philippines', 'Palau', 'Papua New Guinea', 'Poland',
       'Puerto Rico', "Korea, Dem. People's Rep.", 'Portugal', 'Paraguay',
       'West Bank and Gaza', 'French Polynesia', 'Qatar', 'Romania',
       'Russian Federation', 'Rwanda', 'Saudi Arabia', 'Sudan', 'Senegal',
       'Singapore', 'Solomon Islands', 'Sierra Leone', 'El Salvador',
       'San Marino', 'Somalia', 'Serbia', 'South Sudan',
       'Sao Tome and Principe', 'Suriname', 'Slovak Republic', 'Slovenia',
       'Sweden', 'Eswatini', 'Sint Maarten (Dutch part)', 'Seychelles',
       'Syrian Arab Republic', 'Turks and Caicos Islands', 'Chad', 'Togo',
       'Thailand', 'Tajikistan', 'Turkmenistan', 'Timor-Leste', 'Tonga',
       'Trinidad and Tobago', 'Tunisia', 'Turkiye', 'Tuvalu', 'Tanzania',
       'Uganda', 'Ukraine', 'Uruguay', 'United States', 'Uzbekistan',
       'St. Vincent and the Grenadines', 'Venezuela, RB',
       'British Virgin Islands', 'Virgin Islands (U.S.)', 'Vietnam',
       'Vanuatu', 'Samoa', 'Kosovo', 'Yemen, Rep.', 'South Africa',
       'Zambia', 'Zimbabwe'], dtype=object)

In [9]:
len(metadata_country_list)

217

In [13]:
# Lets confirm if the number of coutries we have in our remittance dataset is equal to the number of countries
# we have metadata set
remittance_country_list == metadata_country_list

False

In [14]:
# a dataframe to extract only the countries in metadata country dataset

realcountries = remittance[remittance['country_name'].isin(metadata_country_list)]
realcountries

,Year,country_code,country_name,gdp,new_income_group,new_region,population,remittance_growth_rate,remittance_paid,remittance_per_capita,remittance_received,remittance_to_gdp_ratio,remittance_volatility,unemployment_rate,unemployment_rate_change
0,1970,AFG,Afghanistan,0.000000,Low income,South Asia,10752971.0,0.000000,0.00,0.000000,0.000000e+00,0.000000e+00,2.934855e+08,0.000,0.000
1,1971,AFG,Afghanistan,0.000000,Low income,South Asia,11015857.0,0.000000,0.00,0.000000,0.000000e+00,0.000000e+00,2.934855e+08,0.000,0.000
2,1972,AFG,Afghanistan,0.000000,Low income,South Asia,11286753.0,0.000000,0.00,0.000000,0.000000e+00,0.000000e+00,2.934855e+08,0.000,0.000
3,1973,AFG,Afghanistan,0.000000,Low income,South Asia,11575305.0,0.000000,0.00,0.000000,0.000000e+00,0.000000e+00,2.934855e+08,0.000,0.000
4,1974,AFG,Afghanistan,0.000000,Low income,South Asia,11869879.0,0.000000,0.00,0.000000,0.000000e+00,0.000000e+00,2.934855e+08,0.000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14093,2018,ZWE,Zimbabwe,4.179939,Lower middle income,Sub-Saharan Africa,15052184.0,-17.468271,29278892.45,94.850224,1.427703e+09,3.415607e+08,8.881924e+08,6.784,0.505
14094,2019,ZWE,Zimbabwe,6.490458,Lower middle income,Sub-Saharan Africa,15354608.0,-0.748830,13480565.66,92.285779,1.417012e+09,2.183223e+08,8.881924e+08,7.370,0.586
14095,2020,ZWE,Zimbabwe,8.517271,Lower middle income,Sub-Saharan Africa,15669666.0,29.288915,21707094.03,116.916301,1.832039e+09,2.150970e+08,8.881924e+08,7.898,0.528
14096,2021,ZWE,Zimbabwe,6.985948,Lower middle income,Sub-Saharan Africa,15993524.0,8.185447,0.00,123.925159,1.982000e+09,2.837124e+08,8.881924e+08,8.067,0.169
14097,2022,ZWE,Zimbabwe,9.901347,Lower middle income,Sub-Saharan Africa,16320537.0,3.300000,0.00,125.449671,2.047406e+09,2.067806e+08,8.881924e+08,7.945,-0.122

In [12]:
# checking the total number of the remmitance data
realcountries['country_name'].nunique()

217

In [15]:
# Getting the names of the countries that are not metadata country data set
print(set(remittance_country_list) ^ set(metadata_country_list))

{'Middle East & North Africa (IDA & IBRD countries)', 'IBRD only', 'IDA total', 'Europe & Central Asia (excluding high income)', 'Not classified', 'Latin America & Caribbean (excluding high income)', 'Small states', 'East Asia & Pacific (excluding high income)', 'South Asia', 'Caribbean small states', 'Arab World', 'IDA blend', 'East Asia & Pacific', 'World', 'Post-demographic dividend', 'Lower middle income', 'Africa Western and Central', 'Central Europe and the Baltics', 'Middle East & North Africa (excluding high income)', 'Pre-demographic dividend', 'Europe & Central Asia', 'Low & middle income', 'Sub-Saharan Africa (excluding high income)', 'Low income', 'European Union', 'Least developed countries: UN classification', 'Heavily indebted poor countries (HIPC)', 'South Asia (IDA & IBRD)', 'Sub-Saharan Africa (IDA & IBRD countries)', 'Middle East & North Africa', 'Europe & Central Asia (IDA & IBRD countries)', 'Africa Eastern and Southern', 'IDA only', 'Pacific island small states', 'High income', 'Latin America & the Caribbean (IDA & IBRD countries)', 'Other small states', 'Fragile and conflict affected situations', 'Sub-Saharan Africa', 'North America', 'Upper middle income', 'Latin America & Caribbean', 'East Asia & Pacific (IDA & IBRD countries)', 'Middle income', 'Euro area', 'Late-demographic dividend', 'Early-demographic dividend', 'OECD members', 'IDA & IBRD total'}

In [18]:
#Renaming the column names for better understanding
realcountries.rename(columns={'new_income_group': 'income_group', 'new_region': 'region'}, inplace=True)

In [19]:
realcountries.to_csv(r"C:\Users\chine\Downloads\Catboost Project\Cleaned Data\Remittance 1970 - 2022 -Chinelo.csv", index = False)   #To save to csv